[build]
builder = "nodejs"

[deploy]
startCommand = "npm start"

[environments.production]
variables = { NODE_ENV = "production" }

# Simplified single-phase build for faster deployment
[phases.setup]
cmds = ["echo 'Fast deployment starting...'"]

[phases.install]
cmds = ["npm ci --omit=dev --prefer-offline --no-audit"]

[phases.build]
cmds = ["npx prisma generate --schema=./prisma/schema.prod.prisma"]