[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && npm start"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments]
production = {
  variables = {
    NODE_ENV = "production",
    NIXPACKS_BUILD_CMD = "npm run build"
  }
}

[services]
web = { type = "web" }